---
- name: Restart service
  ansible.builtin.systemd:
    name: "{{ postgresql_service_name }}"
    state: restarted
    daemon_reload: yes
  when:
    - postgresql_service_restart_on_change
    - postgresql_service_state == 'started'
    